version: '2'
services:
  mongodb:
    image: mongo:3.4
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./data/mongodb/db:/data/db"
    restart: always
    ports:
      - "27017:27017"

  telegram-alert:
    build: ./
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=default
      - NODE_CONFIG_DIR=/etc/telegram-alert
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/:/etc/telegram-alert"
    restart: always
    depends_on:
      - mongodb